# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: นักวิจัยกับกาแฟดำแก้วหนึ่ง
name: One Black Coffee Researcher
email: Chanon.khong@mail.kmutt.ac.th
location: Bangkok, Thailand
company: KMUTT
company_url: https://kmutt.ac.th
github_url: https://github.com/chanontonmai
description: This is personnel website of chanon
favicon: icon.jpg # Image must be in assets/images

url: http://chanontonmai.github.io # the base hostname & protocol for your site

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: httpdongchuangithubio.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation
navs:
  -
    href: /
    label: Home

  -
    href: /open-source
    label: Open-Source

  -
    href: /blog
    label: Blog

  -
    href: /bookmark
    label: Bookmark

  -
    href: /about
    label: About

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
#analytics :
#  provider : google
#  google :
#      tracking_id : 'UA-72165600-1'


# For about.html. Fell free to create your own!
skill_software_keywords: [C, C++, Qt, Python, Design Patterns]
skill_j2ee_keywords: [VHDL Vivado/ISE based on Xilinx FPGA, Arduino, Raspberry Pi, ARM-Cortex]
skill_web_keywords: [HTML, CSS, JS, JQuery, Boostrap, Latex]
skill_mobile_app_keywords: [Android, Sketch UI Desgin]
